include:
  - '/.ci/gitlab/common.yml'
  - '/.ci/gitlab/publish.yml'
#   - '/.ci/gitlab/benchmark.yml'

variables:
  # Default GHC / Cabal version. Used for generating Haddock and releasing to
  # Hackage.
  GHC_VERSION: 9.6.7

  # https://docs.gitlab.com/runner/executors/custom.html#system-failure
  GET_SOURCES_ATTEMPTS: 5
  RESTORE_CACHE_ATTEMPTS: 5
  ARTIFACT_DOWNLOAD_ATTEMPTS: 5

stages:
  - pack
