#!/bin/sh
GHC_VERSION=$(ghc --numeric-version)

cabal build clash-lib clash-ghc --only-dependencies

ghci \
  -fobject-code \
  -iclash-ghc/src-bin-common/ \
  -iclash-lib/src \
  -iclash-ghc/src-ghc \
  -Wall -Wcompat -DTOOL_VERSION_ghc=\"${GHC_VERSION}\" \
  -XBangPatterns -XBinaryLiterals -XDataKinds -XDefaultSignatures \
  -XDeriveDataTypeable -XDeriveFoldable -XDeriveFunctor -XDeriveGeneric \
  -XDeriveLift -XDeriveTraversable -XDerivingStrategies -XInstanceSigs \
  -XKindSignatures -XNoStarIsType -XPostfixOperators -XScopedTypeVariables \
  -XStandaloneDeriving -XTupleSections -XTypeApplications -XTypeOperators \
  -XViewPatterns -XNoPolyKinds -DDEBUG \
  Clash.hs
