#!/bin/sh
GHC_VERSION=$(ghc --numeric-version)
GHC_MAJOR_VERSION=$(echo ${GHC_VERSION} | tr -d '.' | head -c2)

if [ ${GHC_MAJOR_VERSION} != 84 ]; then
  XNoStarIsType="-XNoStarIsType"
fi

ghci \
  -fobject-code \
  -iclash-ghc/src-bin-common/ \
  -iclash-lib/src \
  -iclash-ghc/src-ghc \
  -Wall -Wcompat -DTOOL_VERSION_ghc=\"${GHC_VERSION}\" \
  -XBangPatterns -XBinaryLiterals -XDataKinds -XDefaultSignatures \
  -XDeriveDataTypeable -XDeriveFoldable -XDeriveFunctor -XDeriveGeneric \
  -XDeriveLift -XDeriveTraversable -XDerivingStrategies -XInstanceSigs \
  -XKindSignatures ${XNoStarIsType} -XScopedTypeVariables -XStandaloneDeriving \
  -XTupleSections -XTypeApplications -XTypeOperators -XViewPatterns \
  -XNoPolyKinds -DDEBUG \
  Clash.hs
