{-|
  Copyright   :  (C) 2026, QBayLogic B.V.
  License     :  BSD2 (see the file LICENSE)
  Maintainer  :  QBayLogic B.V. <devops@qbaylogic.com>

  Records the package databases @clash-ghc@ is built against in the generated
  module @PackageDbs_clash_ghc@. Clash uses these to find @clash-prelude@ and
  the type checker plugins when no package environment provides them, see
  @Clash.GHC.PackageEnv@.
-}

{-# LANGUAGE DisambiguateRecordFields #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE StaticPointers #-}

module SetupHooks (setupHooks) where

import Control.Monad.IO.Class (liftIO)
import Data.List.NonEmpty (NonEmpty (..))
import Distribution.Simple.Compiler (PackageDBX (..))
import Distribution.Simple.LocalBuildInfo (interpretSymbolicPathLBI, localBuildDescr)
import Distribution.Simple.SetupHooks
import qualified Distribution.Types.LocalBuildConfig as LocalBuildConfig
import Distribution.Utils.Path (makeRelativePathEx)
import System.Directory (createDirectoryIfMissing, makeAbsolute)
import System.FilePath (takeDirectory)

setupHooks :: SetupHooks
setupHooks = noSetupHooks
  { buildHooks = noBuildHooks
      { preBuildComponentRules = Just (rules (static ()) packageDbsRules)
      }
  }

packageDbsRules :: PreBuildComponentInputs -> RulesM ()
packageDbsRules PreBuildComponentInputs{localBuildInfo = lbi, targetInfo} =
  case componentLocalName clbi of
    CLibName LMainLibName -> do
      -- GHC's global and user databases are found without our help
      dbs <- liftIO $ mapM makeAbsolute
        [ interpretSymbolicPathLBI lbi db
        | SpecificPackageDB db <- LocalBuildConfig.withPackageDB
            (LocalBuildConfig.packageBuildDescr (localBuildDescr lbi))
        ]
      let
        out = Location
          (autogenComponentModulesDir lbi clbi)
          (makeRelativePathEx "PackageDbs_clash_ghc.hs")
        command = mkCommand
          (static Dict)
          (static writePackageDbs)
          (interpretSymbolicPathLBI lbi (location out), dbs)
      registerRule_ "PackageDbs_clash_ghc" (staticRule command [] (out :| []))
    _ ->
      pure ()
 where
  clbi = targetCLBI targetInfo

writePackageDbs :: (FilePath, [FilePath]) -> IO ()
writePackageDbs (path, dbs) = do
  createDirectoryIfMissing True (takeDirectory path)
  writeFile path $ unlines
    [ "-- | Generated by clash-ghc's SetupHooks.hs"
    , "module PackageDbs_clash_ghc (packageDbs) where"
    , ""
    , "-- | The package databases clash-ghc was built against, other than GHC's"
    , "-- global and user databases. In command line order."
    , "packageDbs :: [FilePath]"
    , "packageDbs = " <> show dbs
    ]
