#!/bin/bash

unset PROG PROGDIR REALPROG

PROG="$(basename $0)"
PROGDIR="$(dirname $0)"

if [[ -n "$RETRY_GHC_HEISENBUG_LOOP_DETECT" ]]; then
  echo "retry-ghc-heisenbug: Loop detected, aborting" >&2
  exit 1
fi
export RETRY_GHC_HEISENBUG_LOOP_DETECT=1

REALPROG="$(which -a $PROG | tail -n+2 | head -n1)"

if [[ -z "$REALPROG" ]]; then
  echo "retry-ghc-heisenbug: Real $PROG not found, aborting" >&2
  exit 1
fi

"$PROGDIR/../script" "$REALPROG" "$@"
