# A simple pipeline that errors if a PR tries to introduce a new file in changelog/,
# which is presumably an old-style changelog entry.
# The CI only protects master and 1.10.
# This CI is meant to be removed later when there are no more old-style entries
# floating around.

name: changelog-old-format-check

on:
  pull_request:
    branches: [master, 1.10]
    paths:
      - 'changelog/20*'

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check for changelog entries in the wrong folder
        run: |
          old=$(find changelog/ -maxdepth 1 -type f -name '20*')

          if [ -z "$old" ]; then
            exit 0
          else
            echo "::warning title=Old-style changelog entries found::$old"
            exit 1
          fi
